# Generated by Django 5.2.6 on 2025-12-08 10:29

import FristSiteApp.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento'), ('administrativo', 'Administrativo'), ('otros', 'Otros')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField(default=datetime.date.today)),
                ('horario', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Personal Extra',
                'verbose_name_plural': 'Personal Extra',
                'db_table': 'personal_extra',
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('nocturno', 'Nocturno'), ('completo', 'Tiempo Completo')], max_length=50)),
                ('fecha_contratacion', models.DateField(default=FristSiteApp.models.default_fecha_contratacion)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'recepcionista',
            },
        ),
    ]
