# Generated by Django 5.2.6 on 2025-12-08 08:39

import FristSiteApp.models
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FristSiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('mantenimiento', 'Mantenimiento'), ('administrativo', 'Administrativo'), ('otros', 'Otros')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField(default=datetime.date.today)),
                ('horario', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Personal Extra',
                'verbose_name_plural': 'Personal Extra',
                'db_table': 'personal_extra',
            },
        ),
        migrations.AlterField(
            model_name='recepcionista',
            name='fecha_contratacion',
            field=models.DateField(default=FristSiteApp.models.default_fecha_contratacion),
        ),
    ]
