# Generated by Django 5.2.6 on 2025-12-15 02:17

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FristSiteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especialidad', models.CharField(max_length=100)),
                ('cedula_profesional', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion_consultorio', models.TextField()),
                ('horario_atencion', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField(default=datetime.date.today)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='medicos_fotos/')),
                ('estado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
            },
        ),
    ]
