# Generated by Django 5.2.6 on 2025-12-17 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FristSiteApp', '0003_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('mañana', 'Mañana (6:00 AM - 12:00 PM)'), ('tarde', 'Tarde (12:00 PM - 6:00 PM)'), ('noche', 'Noche (6:00 PM - 12:00 AM)')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_consulta', models.CharField(choices=[('general', 'Consulta General'), ('especialidad', 'Consulta de Especialidad'), ('seguimiento', 'Consulta de Seguimiento'), ('emergencia', 'Emergencia'), ('examen', 'Examen'), ('terapia', 'Terapia')], max_length=50)),
                ('motivo', models.TextField()),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('diagnostico_previo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='agendada', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('emergencia', 'Emergencia')], default='normal', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='FristSiteApp.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='FristSiteApp.paciente')),
                ('recepcionista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agendadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'cita',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('medico', 'fecha', 'hora_inicio')},
            },
        ),
    ]
